using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;

/// <summary>
/// AC
/// </summary>
public class EllysFigurines
{
	int n, m;
	int R, C;
	string[] board;

	public int getMoves(string[] board, int R, int C)
	{
		n = board.Length;
		m = board[0].Length;

		this.R = R;
		this.C = C;
		this.board = board;

		int[] cols = new int[m];
		for (int j = 0; j < m; j++)
			for (int i = 0; i < n; i++)
				if (board[i][j] == 'X')
					cols[j]++;

		return res(0, cols);
	}

	int res(int s, int[] cols)
	{
		int trivialCols = 0;
		for (int j = 0; j < m; )
			if (cols[j] > 0)
			{
				trivialCols++;
				j += C;
			}
			else
				j++;

		if (trivialCols == 0)
			return 0;

		int min = int.MaxValue;
		for (int i = s; i < n; i++)
		{
			// remove up to R rows starting from i-th
			int[] newcols = (int[])cols.Clone();

			for (int k = i; k < i + R && k < n; k++)
			{
				// k-th row is removed.
				for (int j = 0; j < m; j++)
					if (board[k][j] == 'X')
					{
						newcols[j]--;
						if (newcols[j] < 0)
							throw new Exception();
					}
			}

			int cur = 1 + res(i + R, newcols);
			min = Math.Min(cur, min);
		}

		return Math.Min(min, trivialCols);
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	#region Testing code generated by KawigiEdit
	[STAThread]
	private static Boolean KawigiEdit_RunTest(int testNum, string[] p0, int p1, int p2, Boolean hasAnswer, int p3)
	{
		Console.Write("Test " + testNum + ": [" + "{");
		for (int i = 0; p0.Length > i; ++i)
		{
			if (i > 0)
			{
				Console.Write(",");
			}
			Console.Write("\"" + p0[i] + "\"");
		}
		Console.Write("}" + "," + p1 + "," + p2);
		Console.WriteLine("]");
		EllysFigurines obj;
		int answer;
		obj = new EllysFigurines();
		DateTime startTime = DateTime.Now;
		answer = obj.getMoves(p0, p1, p2);
		DateTime endTime = DateTime.Now;
		Boolean res;
		res = true;
		Console.WriteLine("Time: " + (endTime - startTime).TotalSeconds + " seconds");
		if (hasAnswer)
		{
			Console.WriteLine("Desired answer:");
			Console.WriteLine("\t" + p3);
		}
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + answer);
		if (hasAnswer)
		{
			res = answer == p3;
		}
		if (!res)
		{
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else if ((endTime - startTime).TotalSeconds >= 2)
		{
			Console.WriteLine("FAIL the timeout");
			res = false;
		}
		else if (hasAnswer)
		{
			Console.WriteLine("Match :-)");
		}
		else
		{
			Console.WriteLine("OK, but is it right?");
		}
		Console.WriteLine("");
		return res;
	}
	public static void Main(string[] args)
	{
		Boolean all_right;
		all_right = true;

		string[] p0;
		int p1;
		int p2;
		int p3;

		// ----- test 0 -----
		p0 = new string[] { 
			".X.X.", 
			"XX..X", 
			".XXX.", 
			"...X.", 
			".X.XX" };

		p1 = 1;
		p2 = 2;
		p3 = 3;
		all_right = KawigiEdit_RunTest(0, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = new string[] { 
			".X.X.", 
			"XX..X", 
			".X.X.", 
			"...X.", 
			".X.XX" };

		p1 = 2;
		p2 = 2;
		p3 = 2;
		all_right = KawigiEdit_RunTest(1, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = new string[] { "XXXXXXX" };
		p1 = 2;
		p2 = 3;
		p3 = 1;
		all_right = KawigiEdit_RunTest(2, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = new string[] 
{ 
	"XXXXX", 
	"X....", 
	"XXX..", 
	"X....", 
	"XXXXX" };

		p1 = 1;
		p2 = 1;
		p3 = 4;
		all_right = KawigiEdit_RunTest(3, p0, p1, p2, true, p3) && all_right;
		// ------------------

		// ----- test 4 -----
		p0 = new string[] { 
			"XXX..XXX..XXX.", 
			".X..X....X...X", 
			".X..X....X...X", 
			".X..X....X...X", 
			".X...XXX..XXX.", 
			"..............", 
			"...XX...XXX...", 
			"....X......X..", 
			"....X....XXX..", 
			"....X......X..", 
			"...XXX..XXX..." };

		p1 = 1;
		p2 = 2;
		p3 = 7;
		all_right = KawigiEdit_RunTest(4, p0, p1, p2, true, p3) && all_right;
		// ------------------

		if (all_right)
		{
			Console.WriteLine("You're a stud (at least on the example cases)!");
		}
		else
		{
			Console.WriteLine("Some of the test cases had errors.");
		}
	}
	#endregion
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
