using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;


public class EllysScrabble
{
	public string getMin(string letters, int md)
	{
		int n = letters.Length;
		char[] a = letters.ToCharArray();
		bool[] used = new bool[n];
		char[] res = new char[n];

		for (int i = 0; i < n; i++)
		{
			char min = ' ';
			int minj = 0;
			if (i - md >= 0 && !used[i - md])
			{
				min = a[i - md];
				minj = i - md;
			}
			else
				for (int j = Math.Max(0, i - md); j <= Math.Min(n - 1, i + md); j++)
					if (!used[j] && (min == ' ' || a[j] < min))
					{
						min = a[j];
						minj = j;
					}
			res[i] = min;
			used[minj] = true;
		}

		return new string(res);
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	#region Testing code generated by KawigiEdit
	[STAThread]
	private static Boolean KawigiEdit_RunTest(int testNum, string p0, int p1, Boolean hasAnswer, string p2)
	{
		Console.Write("Test " + testNum + ": [" + "\"" + p0 + "\"" + "," + p1);
		Console.WriteLine("]");
		EllysScrabble obj;
		string answer;
		obj = new EllysScrabble();
		DateTime startTime = DateTime.Now;
		answer = obj.getMin(p0, p1);
		DateTime endTime = DateTime.Now;
		Boolean res;
		res = true;
		Console.WriteLine("Time: " + (endTime - startTime).TotalSeconds + " seconds");
		if (hasAnswer)
		{
			Console.WriteLine("Desired answer:");
			Console.WriteLine("\t" + "\"" + p2 + "\"");
		}
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + "\"" + answer + "\"");
		if (hasAnswer)
		{
			res = answer == p2;
		}
		if (!res)
		{
			Console.WriteLine("DOESN'T MATCH!!!!");
		}
		else if ((endTime - startTime).TotalSeconds >= 2)
		{
			Console.WriteLine("FAIL the timeout");
			res = false;
		}
		else if (hasAnswer)
		{
			Console.WriteLine("Match :-)");
		}
		else
		{
			Console.WriteLine("OK, but is it right?");
		}
		Console.WriteLine("");
		return res;
	}
	public static void Main(string[] args)
	{
		Boolean all_right;
		all_right = true;

		string p0;
		int p1;
		string p2;

		// ----- test 0 -----
		p0 = "TOPCODER";
		p1 = 3;
		p2 = "CODTEPOR";
		all_right = KawigiEdit_RunTest(0, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 1 -----
		p0 = "ESPRIT";
		p1 = 3;
		p2 = "EIPRST";
		all_right = KawigiEdit_RunTest(1, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 2 -----
		p0 = "BAZINGA";
		p1 = 8;
		p2 = "AABGINZ";
		all_right = KawigiEdit_RunTest(2, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 3 -----
		p0 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		p1 = 9;
		p2 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
		all_right = KawigiEdit_RunTest(3, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 4 -----
		p0 = "GOODLUCKANDHAVEFUN";
		p1 = 7;
		p2 = "CADDGAHEOOFLUKNNUV";
		all_right = KawigiEdit_RunTest(4, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 5 -----
		p0 = "AAAWDIUAOIWDESBEAIWODJAWDBPOAWDUISAWDOOPAWD";
		p1 = 6;
		p2 = "AAAADDEIBWAEUIODWADSBIAJWODIAWDOPOAWDUOSPWW";
		all_right = KawigiEdit_RunTest(5, p0, p1, true, p2) && all_right;
		// ------------------

		// ----- test 6 -----
		p0 = "ABRACADABRA";
		p1 = 2;
		p2 = "AABARACBDAR";
		all_right = KawigiEdit_RunTest(6, p0, p1, true, p2) && all_right;
		// ------------------

		if (all_right)
		{
			Console.WriteLine("You're a stud (at least on the example cases)!");
		}
		else
		{
			Console.WriteLine("Some of the test cases had errors.");
		}
	}
	#endregion
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
