using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.Text;
using System.Text.RegularExpressions;


public class TheNumberGameDivTwo
{
	int []D;

	public string find(int n)
	{
	
		D = new int[n + 1];
		for (int i = 0;i <= n;i++)
				D[i] = -1;
				
		return res(n)  == 0 ? "John" : "Brus";
	}
	
	int res(int n)
	{
		if (D[n] != -1)
			return D[n];
			
		bool win = false;
		for (int d = 2;d*d <= n;d++)
			if (n % d == 0)
			{
				int d1 = n / d;
				int d2 = d;
				
				int n1 = n - d1;
				int n2 = n - d2;
				
				if (res(n1) == 1 || res(n2) == 1)
				{
					win = true;
					break;
				}
			}
			
		D[n] = win ? 0 : 1;
		return D[n];
	}

	// BEGIN KAWIGIEDIT TESTING
	// Generated by KawigiEdit 2.1.4 (beta) modified by pivanof
	#region Testing code generated by KawigiEdit
	[STAThread]
	private static Boolean KawigiEdit_RunTest(int testNum, int p0, Boolean hasAnswer, string p1) {
		Console.Write("Test " + testNum + ": [" + p0);
		Console.WriteLine("]");
		TheNumberGameDivTwo obj;
		string answer;
		obj = new TheNumberGameDivTwo();
		DateTime startTime = DateTime.Now;
		answer = obj.find(p0);
		DateTime endTime = DateTime.Now;
		Boolean res;
		res = true;
		Console.WriteLine("Time: " + (endTime - startTime).TotalSeconds + " seconds");
		if (hasAnswer) {
			Console.WriteLine("Desired answer:");
			Console.WriteLine("\t" + "\"" + p1 + "\"");
		}
		Console.WriteLine("Your answer:");
		Console.WriteLine("\t" + "\"" + answer + "\"");
		if (hasAnswer) {
			res = answer == p1;
		}
		if (!res) {
			Console.WriteLine("DOESN'T MATCH!!!!");
		} else if ((endTime - startTime).TotalSeconds >= 2) {
			Console.WriteLine("FAIL the timeout");
			res = false;
		} else if (hasAnswer) {
			Console.WriteLine("Match :-)");
		} else {
			Console.WriteLine("OK, but is it right?");
		}
		Console.WriteLine("");
		return res;
	}
	public static void Main(string[] args) {
		Boolean all_right;
		all_right = true;
		
		int p0;
		string p1;
		
		// ----- test 0 -----
		p0 = 6;
		p1 = "John";
		all_right = KawigiEdit_RunTest(0, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 1 -----
		p0 = 2;
		p1 = "Brus";
		all_right = KawigiEdit_RunTest(1, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 2 -----
		p0 = 747;
		p1 = "Brus";
		all_right = KawigiEdit_RunTest(2, p0, true, p1) && all_right;
		// ------------------
		
		// ----- test 3 -----
		p0 = 128;
		p1 = "Brus";
		all_right = KawigiEdit_RunTest(3, p0, true, p1) && all_right;
		// ------------------
		
		if (all_right) {
			Console.WriteLine("You're a stud (at least on the example cases)!");
		} else {
			Console.WriteLine("Some of the test cases had errors.");
		}
	}
	#endregion
	// END KAWIGIEDIT TESTING
}
//Powered by KawigiEdit 2.1.4 (beta) modified by pivanof!
